# -*- coding: utf-8 -*-
"""send.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g0D2Nb4en9eXMATXxpP_DtcFuF4vcWrN
"""

# import pip
# !pip install pygrok
from matplotlib import pyplot as plt
import numpy as np


listAll = []
tmp = 1
with open('/content/output.txt', 'rb') as f:
 for line in f:
   findIndex = line.find('received'.encode())
   if findIndex != -1:
     initVal = int(line[findIndex+9:findIndex+14].decode('utf-8'))
     initVal = initVal * tmp
     listAll.append(initVal)
     tmp = tmp + 1

print(len(listAll))
time = []
tmp = 0
for i in listAll:
  tmp = tmp + 1
  time.append(tmp)


#  # plot the graph        
plt.plot(time,listAll,'ro')
plt.xlabel('time axis')
plt.ylabel('Data axis')  
plt.title('Data flow')
plt.legend(loc='upper right')
plt.show()